#!/bin/bash

# Prompt the user for a number
read -p "Enter a number: " my_number

# Print the number back
echo "You entered: $my_number"
echo " now  wait for 2 seconds"
sleep 2
if (($my_number>=10)); then
echo " big number"
else
echo "less than 10"
fi
